name: Check compliation

on:
  push:
    branches: 
      - master

jobs:
  compilation:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    steps:
    - uses: actions/checkout@v2
    - name: Make a projet
      run: make
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        allow_failure: true
        files: "montest.epitech"
