name: Run Func

on:
  workflow_run:
    workflows: [Run tests]
    types:
      - completed

jobs:
  functional-tests:
    runs-on: self-hosted
    container: epitechcontent/epitest-docker:devel
    steps:
    - uses: actions/checkout@v2
    - name: Make a projet
      run: make
    - name: Run tests
      run: ./test.sh
