name: Run tests

on:
  workflow_run:
    workflows: [Check compliation]
    types:
      - completed

jobs:
  unit-tests:
    runs-on: self-hosted
    container: epitechcontent/epitest-docker:devel
    steps:
    - uses: actions/checkout@v2
    - name: Make a projet
      run: make tests_run
    - name: Display coverage
      run: make coverage
